accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/',views.signup, name='signup'),
]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('memos/', include('memo.urls')),
]

memo/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'memos'
urlpatterns = [
    path('',views.index, name='list'),
    path('create/',views.create, name='create'),
    path('<int:memo_id>/update/',views.update,name='update'),
    path('<int:memo_id>/delete/',views.delete,name='delete'),
    path('<int:memo_id>/like/',views.like,name='like'),
    path('<int:user_id>/',views.people,name='people'),
]

accounts/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Profile(models.Model) :
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=50, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(blank=True)

memo/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Memo(models.Model) :
    title = models.CharField(max_length=50)
    content = models.TextField()
    # TODO : 태그목록 추가
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # Meom는 자신을 좋아하는 user를 like_users로 조회
    # User는 자신이 좋아하는 memo를 like_memos로 조회
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL,related_name='like_memos', blank=True)

    def __str__(self) :
        return f'{self.id} | {self.title} | {self.user}'

accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model
from django import forms
from .models import Profile
from django.utils.translation import gettext_lazy as _

class CustomUserCreationForm(UserCreationForm) :
    class Meta(UserCreationForm.Meta) :
        model = get_user_model()

class CustomProfileCreationForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["nickname"]
        widgets = {
            'nickname' : forms.TextInput(
                attrs = {
                    'placeholder' : '닉네임'
                }
            )
        }
        labels = {
            'nickname': _('닉네임'),
        }
        help_texts = {
            'nickname': _('닉네임을 입력해주세요.'),
        }

class CustomProfileChangeForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["nickname","description","image"]
        

memo/forms.py
from django import forms 
from .models import Memo 

class MemoForm(forms.ModelForm):
    class Meta :
        model = Memo
        fields = ["title","content",]
        widgets={
            "title" : forms.TextInput(
                attrs={
                    "class" : "form-control",
                    "placeholder" : "제목을 입력하세요."
                }),
            "content" : forms.Textarea(
                attrs={
                    "class" : "form-control",
                    "placeholder" : "내용을 입력하세요."
                })
        }

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from .forms import CustomUserCreationForm, CustomProfileCreationForm
from .models import Profile

# Create your views here.
def login(request) :
    if request.method == 'POST' :
        form = AuthenticationForm(request, request.POST)

        if form.is_valid() :
            # 로그인하여 원래 주소로 넘겨주기
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'memos:list')

    form = AuthenticationForm()
    content = {
        'form' :form,
    }
    return render(request,'accounts/login.html',content)

def logout(request) :
    auth_logout(request)
    return redirect('memos:list')


def signup(request) :
    if request.method =='POST' :
        user_form = CustomUserCreationForm(request.POST)
        profile_form = CustomProfileCreationForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid() :
            user = user_form.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()

            # Profile.objects.create(user=user,nickname=user.username)
            return redirect('accounts:login')

    user_form = CustomUserCreationForm()
    profile_form = CustomProfileCreationForm()
    content = {
        'user_form' : user_form,
        'profile_form' : profile_form,
    }
    return render(request,'accounts/signup.html',content)

memo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Memo
from .forms import MemoForm

# Create your views here.
def index(request) :
    memos = Memo.objects.all()
    content = {
        'memos' : memos
    }
    return render(request,'memos/list.html', content)

@login_required
def create(request) :
    if request.method == 'POST' :
        form = MemoForm(request.POST)
        if form.is_valid() :
            memo = form.save(commit=False)
            memo.user = request.user
            memo.save()
            return redirect('memos:list')
    form = MemoForm()
    content = {
        'form' :form,
    }
    return render(request,'memos/create.html', content)

@login_required
def update(request, memo_id):
    memo = get_object_or_404(Memo, pk=memo_id)
    if request.method == 'POST' :
        form = MemoForm(request.POST, instance=memo)
        if form.is_valid() :
            form.save()
            return redirect('memos:list')
    form = MemoForm(instance=memo)
    content = {
        'form' :form,
    }
    return render(request,'memos/update.html',content)

@login_required
def delete(request,memo_id) :
    memo = get_object_or_404(Memo,pk=memo_id)
    if request.method == 'POST' :
        memo.delete()
    return redirect('memos:list')

@login_required
def like(request,memo_id) :
    memo = get_object_or_404(Memo,pk=memo_id)
    if request.user in memo.like_users.all() :
        memo.like_users.remove(request.user)
    else :
        memo.like_users.add(request.user)
    return redirect('memos:list')

@login_required
def people(request,user_id) :
    # user = get_object_or_404(get_user_model(),pk=user_id)
    # content = {
    #     'user' : user,
    # }
    return render(request, 'memos/people.html')

accounts/templates/accounts/login.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block body %}
<div class="container pt-100px">
    <div class="row align-items-center h-fix">
        <div class="col-lg-6">
            <!-- TODO : 메모장 미리보기 -->
            <div class="card preview-card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-9">
                            <h5 class="card-title">Live in the Moment</h5>
                            <h6 class="card-subtitle mb-2 text-muted">Do focus on what is happening right now, and Do not worry about the past or the future.</h6>
                        </div>
                        <div class="col-3 text-center like-field pt-1">
                            <i class="fas fa-heart"></i>
                            <p class="pt-1">좋아요 1K개</p>
                        </div>
                        <!-- <div class="col-12">
                            <span class="badge badge-primary">Enjoy</span>
                            <span class="badge badge-secondary">Sweet</span>
                            <span class="badge badge-success">Success</span>
                            <span class="badge badge-danger">Love</span>
                            <span class="badge badge-warning">Happy</span>
                            <span class="badge badge-info">Info</span>
                            <span class="badge badge-light">Light</span>
                            <span class="badge badge-dark">Dark</span>
                        </div> -->
                    </div>
                    <p class="card-text">
                        <br/>
                        자유롭게 메모하고 공유하세요! 
                        <br/>
                        익명의 사람뿐만 아니라 자신을 위해, 순간의 감정과 기억을 기록하세요.
                        <br/>
                        <br/>
                        Feel free to write and share! 
                        <br/>
                        You can write moments of memory and emotion for anonymous people and yourself.
                    </p>
                    <!-- <div class="card-link text-right">
                        <a class="github-button" href="https://github.com/naye0ng" aria-label="Follow @naye0ng on GitHub">Follow</a>
                        <a class="github-button" href="https://github.com/naye0ng/Personal-or-Group-Notes-App" aria-label="Star naye0ng/Personal-or-Group-Notes-App on GitHub">Star</a>
                    </div>     -->
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <form method='POST'>
                {% csrf_token %}
                <!-- 모델 폼 -->
                {% bootstrap_form form %}
                <button type='submit' class='btn btn-primary'>로그인</button>
            </form>
        </div>
    </div>
</div>
{% endblock body %}

accounts/templates/accounts/people.html
{% extends "base.html" %}

{% block body %}

{% endblock body %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block body %}
<div class="container pt-100px">
    <div class="row align-items-center h-fix">
        <div class="col-lg-6">
            <!-- TODO : 메모장 미리보기 -->
            <div class="card preview-card">
                <div class="card-body">
                    <h5 class="card-title"></h5>
                    <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
                    <span class="badge badge-warning">Health</span>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <a href="#" class="card-link">Card link</a>
                    <a href="#" class="card-link">Another link</a>
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <form method='POST' >
            {% csrf_token %}
            {% bootstrap_form user_form %}
            {% bootstrap_form profile_form %}
            <button type='submit' class='btn btn-primary'>회원가입</button>
            </form>
        </div>
    </div>
</div>
{% endblock body %}

memo/templates/memos/create.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block body %}
<div class="container pt-100px">
    <form method='POST' >
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type='submit' class='btn btn-primary'>등록</button>
    </form>  
</div>
{% endblock body %}

memo/templates/memos/list.html
{% extends "base.html" %}

{% load static %}

{% block body %}
<!-- 조회 및 설명 -->
<section id='memo-list-info-section'>
    <div class="container h-100 d-flex justify-content-center align-items-center">
    <div class="row text-center">
        <div class="memo-title col-12">
            <img src="{% static 'image/memologo.png' %}" alt="" />
            <br>
            <br>
        </div>
        <div class="memo-description col-12">
            <p>
                자유롭게 메모하고 공유하세요! 
                <br>
                개인 혹은 단체, 익명의 모두에게 메모를 작성할 수 있습니다.
            </p>
            <p>
                Feel free to write and share!
                <br>
                You can write notes for individuals, organizations, and anonymous people.
            </p>
        </div>
        <div class="memo-share-btn col-12">
            <br>
            <br>
            <!-- Place this tag where you want the button to render. -->
            <a class="github-button" href="https://github.com/naye0ng/Personal-or-Group-Notes-App" aria-label="Star naye0ng/Personal-or-Group-Notes-App on GitHub">Star</a>
        </div>
    </div>
    </div>
</section>
<!-- card section -->
<section id="memo-list-card-section">
    <div class="container">
        <section class="card-columns">
        {% for memo in memos %}
            <div class="card gradient-border">
                <div class="card-body">
                    <div class="row">
                        <div class="col-9">
                            <h5 class="card-title">{{ memo.title }}</h5>
                            <p class="card-subtitle mb-2 text-muted">{{ memo.updated_at }}</p>
                            <p class="card-subtitle mb-2 text-muted">{{ memo.user }}님의 글</p>
                        </div>
                        <div class="col-3 text-center like-field pt-1">
                            <a href="{% url 'memos:like' memo.id %}">
                                {% if user in memo.like_users.all %}
                                <i class="fas fa-heart"></i>
                                {% else %}
                                <i class="far fa-heart"></i>
                                {% endif %}
                            </a>
                            <p class="pt-1">좋아요 {{ memo.like_users.count }}개</p>
                        </div>
                    </div>
                    <!-- <span class="badge badge-warning">Health</span> -->
                    <p class="card-text">{{ memo.content }}</p>
                    {% if user == memo.user %}
                    <div class="card-btn">
                        <a href="{% url 'memos:update' memo.id %}" class="btn btn-outline-secondary btn-sm">수정</a>
                        <form action="{% url 'memos:delete' memo.id %}" method="POST" class="d-inline">
                            {% csrf_token %}
                            <input type="submit" class="btn btn-outline-secondary btn-sm" value="삭제">
                        </form>
                    </div>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
        </section>
    </div>
</section>

<!-- scroll control -->
<script>
    var ovf, slider;
    $(function(){
        ovf = this.getElementById("memo-list-card-section");
        slider = this.getElementById("memo-list-info-section");
        winResize();
        $(window).bind({resize: winResize, scroll: winScroll});
    });
    function winResize(){
        ovf.style.top = slider.offsetHeight + "px";
    }

    function winScroll(){
        var op = 1 - (window.pageYOffset / slider.offsetHeight);
        slider.style.opacity = op;
    }
</script>
{% endblock body %}

memo/templates/memos/people.html
{% extends "base.html" %}

{% load static %}

{% block body %}
<!-- Profile section -->
<section id='profile-section'>
    <div class="container pt-100px h-100 d-flex justify-content-center">
        <div class="row profile-content">
            <div class="col-4 align-items-start">
                <div class="profile-image ml-auto">
                    {% if user.profile.image %}
                    <img src="{{ user.profile.image.url }}" alt="">
                    {% else %}
                    <img src="{% static 'image/user.png' %}" alt="profile" class="" />
                    {% endif %}
                </div>
            </div>
            <div class="col-8">
                <p class="profile-nickname">{{ user.profile.nickname }}</p>
                <p class="post-liked">
                    <span>게시물 {{ user.memo_set.all.count }}</span>
                    <span>좋아요 {{ user.like_memos.all.count }}</span>
                </p>
                <p class="profile-description">{{ user.profile.description }}
                    dsjkjdksjkdjskjdksjdjsjdksjdkjsdkjskdjksjd
                    dsjkjdksjkdjskjdksjdjsjdksjdkjsdkjskdjksjd
                </p>
            </div>
        </div>
    </div>
</section>
<!-- memo section -->
<section id="memo-section">
    <div class="container">
        <div class="menubar">
            <a href="" style="font-size:10px;" data-toggle="tooltip" data-placement="top" title="작성한 게시물">
                <span>POSTS</span>
            </a>
            <a href="" data-toggle="tooltip" data-placement="top" title="좋아하는 게시물">
                <span>LIKED</span>
            </a>
        </div>
        <div class="card-columns">
        {% for memo in user.memo_set.all %}
            <div class="card gradient-border">
                <div class="card-body">
                    <div class="row">
                        <div class="col-9">
                            <h5 class="card-title">{{ memo.title }}</h5>
                            <p class="card-subtitle mb-2 text-muted">{{ memo.updated_at }}</p>
                            <p class="card-subtitle mb-2 text-muted">{{ memo.user.profile.nickname }}님의 글</p>
                        </div>
                        <div class="col-3 text-center like-field pt-1">
                            <a href="{% url 'memos:like' memo.id %}">
                                {% if user in memo.like_users.all %}
                                <i class="fas fa-heart"></i>
                                {% else %}
                                <i class="far fa-heart"></i>
                                {% endif %}
                            </a>
                            <p class="pt-1">좋아요 {{ memo.like_users.count }}개</p>
                        </div>
                    </div>
                    <!-- <span class="badge badge-warning">Health</span> -->
                    <p class="card-text">{{ memo.content }}</p>
                    {% if user == memo.user %}
                    <div class="card-btn text-right">
                        <a href="{% url 'memos:update' memo.id %}" class="btn btn-outline-secondary btn-sm">수정</a>
                        <form action="{% url 'memos:delete' memo.id %}" method="POST" class="d-inline">
                            {% csrf_token %}
                            <input type="submit" class="btn btn-outline-secondary btn-sm" value="삭제">
                        </form>
                    </div>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
</section>

<script>
    // scroll control
    var ovf, slider;
    $(function(){
        ovf = this.getElementById("memo-section");
        slider = this.getElementById("profile-section");
        winResize();
        $(window).bind({resize: winResize, scroll: winScroll});
    });
    function winResize(){
        ovf.style.top = slider.offsetHeight + "px";
    }

    function winScroll(){
        var op = 1 - (window.pageYOffset / slider.offsetHeight);
        slider.style.opacity = op;
    }
    // Tooltips
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })
</script>

{% endblock body %}

memo/templates/memos/update.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block body %}
<div class="container pt-100px">
    <form method='POST' >
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type='submit' class='btn btn-primary'>수정</button>
    </form>  
</div>
{% endblock body %}

templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
    <!-- Custom CSS -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- Spoqa Font-->
    <link href='//spoqa.github.io/spoqa-han-sans/css/SpoqaHanSans-kr.css' rel='stylesheet' type='text/css'>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <!-- jQuery-->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Githun star button -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>
</head>
<body>
    <!--navbar-->
    {% include "nav.html" %}

    {% block body %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- first Popper.js, then Bootstrap JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-md">
  <a href="{% url 'memos:list' %}">
    <span class="navbar-brand">MOMENT</span>
    <br>
    <span class="navbae-brand-top">Live in the Moment</span>
  </a>
  <button class="navbar-toggler navbar-light bg-light" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a href="{% url 'memos:create' %}" class="btn my-2 my-sm-0">새 글</a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item active">
        <a href="{% url 'memos:people' user.id %}" class="btn my-2 my-sm-0">마이페이지</a>
      </li>
      <li class="nav-item active">
        <a href="{% url 'accounts:logout' %}" class="btn my-2 my-sm-0">로그아웃</a>
      </li>
      {% else %}
      <li class="nav-item active">
        <a href="{% url 'accounts:login' %}" class="btn my-2 my-sm-0" >로그인</a>
      </li>
      <li class="nav-item active">
       <a href="{% url 'accounts:signup' %}" class="btn my-2 my-sm-0" >회원가입</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>